### ISSUE TITLE
foundation.json could not be read correct on Windows. 

### ISSUE THREAD

**Issue by johanneshahn** [EpicCash/epic#12]
https://github.com/EpicCash/epic/blob/4d6f9830fba493e6927d20ad69dda2cfb8a685c5/core/src/core/foundation.rs#L66

the code adds to much buffer for Windows and can't read exact line.

from debug log: \"},\"key_id\":\"0300000000000000000000007500000000\**-- -this is to much-->"}\n{"<----**

20201128 18:04:50.816 DEBUG epic_servers::common::adapters - Received block 9883bdb312ec at 2896 from 3.95.146.171:13414 [in/out/kern: 0/1/1] going to process.
20201128 18:04:50.837 INFO epic_core::core::foundation - buffer str "\"output\":{\"features\":\"Coinbase\",\"commit\":\"091f462dc596e5f1c236fb3b86a125d6d934501b9164fcc450a6a6e27800dd7589\",\"proof\":\"7b3ea8cc1e6ea24403a809dc2b82dd335261606f9078d82e07a50240d4a127ecead8758b72ac558276f48031751f363523e0e2086b5c97a7728b86e3e4d65843040e1ac8311509dfade29367b857269ad8cd800b01e94f9d418e102c4c842ebc9a49822e439fc6ff1b8c140f747ca1c1ee71f1d0ca2f4d310611846f40e6447a194d1e616a1fb995938ac93e34e8c3a091bdfb47691704e1cc6cd8d083e16fea92ef7ab5d202dcd04235851e55ea3c2553e35694ef716f366dd83bc3bcb0bd0dd740d9496928a5f34ec7e19692d9a3febffeeb174dbd74924a6547a3f6c1081026c2f5a08b6d65cfd576ccce1f0711fc3fe7b6e1a4377c290a43f7d49104e8d7493642425209bd19e58d0c64441bf1260ab3678023e68ddec89a93ca17c2d0a02a6479db1c780b383b75259dcf6e443c37c3900f923a823574f022ad85a4a6afc845ec27e08ff270e426736b4401a65d7e4d7ca368a10a479dde7dc548d76e050e470147d462a605ef7de2ddfe430677804cd76ed97ee54b96fdd9c2be698a194995b379f80a7bfcdea69aad6abadd02f4d290e1aa5633ef8ed5ff94d52a5785cd4e6ceb1877842e32987c833f1fbfdb0d1be1516f3c04922e7312735690269a005a4de38a598036dd4c836cd944783ab8a1a8b863b9f51c1db5dd019e1080982ac1e64c21d403c7ec02e9863efb17773f88c4a358bdac6a8b711fc6e0409dcc90084ed5fe5f535914f8865f602ce925d96aabf9e61ba39fe6b92e8268886e0063576210e815d05a26a8b14607c581e630d8da9b0e2abdb2441301fc9489375146ffa7e42c6c7c6fd3dca25566b4a62e481b1c64ee9dcbbfb9405f3c13bb7d72bb29b2b3cb19dcf0c602f0e7f64d734c0d4108bb35aeb32306ba1f8357bbf6031c80d06e0e17abb9015570ab82609f0ad94955461c9d86a4e31ee6be7c43f14cf9a522\"},\"kernel\":{\"features\":\"Coinbase\",\"excess\":\"08ef57989b1103e5d8fff8ace2630004821d73143da5c1be473827bb3863116ef6\",\"excess_sig\":\"41ab4765809c64c6331d724ff52ecc2e2a77b01042613791b8f0240836af544b2e2ec9abb22540d2ce00b3a65afaddb13696070523ea3c7e4279889a74d23829\"},\"key_id\":\"0300000000000000000000007500000000\**"}\n{"**
20201128 18:04:50.875 ERROR epic_util::logger -
thread 'peer_read' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"output\", expected struct CbData", line: 1, column: 8)': core\src\core\foundation.rs:106   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: epic_util::logger::init_logger
   3: std::panicking::rust_panic_with_hook
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\panicking.rs:515
   4: std::panicking::begin_panic_handler
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\panicking.rs:419
   5: core::panicking::panic_fmt
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libcore\panicking.rs:111
   6: core::option::expect_none_failed
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libcore\option.rs:1211
   7: epic_core::core::foundation::load_foundation_output
   8: epic_core::core::block::Block::verify_coinbase
   9: epic_core::core::block::Block::validate
  10: epic_chain::pipe::process_block
  11: epic_chain::chain::Chain::process_block
  12: epic_chain::chain::Chain::process_block
  13: epic_servers::common::adapters::NetToChainAdapter::init
  14: <epic_servers::common::adapters::NetToChainAdapter as epic_p2p::types::ChainAdapter>::block_received
  15: <epic_p2p::peers::Peers as epic_p2p::types::ChainAdapter>::block_received
  16: <epic_p2p::peer::TrackingAdapter as epic_p2p::types::ChainAdapter>::block_received
  17: <epic_p2p::protocol::Protocol as epic_p2p::conn::MessageHandler>::consume
  18: std::sys_common::backtrace::__rust_begin_short_backtrace
  19: std::sync::mpsc::shared::Packet<T>::drop_port
  20: alloc::boxed::{{impl}}::call_once<(),FnOnce<()>>
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\liballoc\boxed.rs:1017
  21: alloc::boxed::{{impl}}::call_once
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\liballoc\boxed.rs:1017
  22: std::sys_common::thread::start_thread
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\sys_common\thread.rs:13
  23: std::sys::windows::thread::{{impl}}::new::thread_start
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\sys\windows\thread.rs:51
  24: BaseThreadInitThunk
  25: RtlUserThreadStart

Thread 'peer_read' panicked with message:
"called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"output\", expected struct CbData", line: 1, column: 8)"

**Comment by johanneshahn** [comment]
fixed in #3.0.0-beta
